@echo off
echo Starting Next.js development server...
start /B npm run dev-next
echo Waiting for server to start...
timeout /t 4 /nobreak > nul
echo Opening browser...
start http://localhost:3000
echo Browser should open automatically. If not, navigate to http://localhost:3000
