@echo off
echo 🚀 Starting Next.js development server with auto-open...
start /B npm run dev-server
echo ⏳ Waiting for server to start...
timeout /t 5 /nobreak > nul
echo 🌐 Opening browser...
start http://localhost:3000
echo ✅ Done! Browser should open automatically.
